# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Country.create(name: 'Türkiye')
Country.create(name: 'ABD Virgin Adaları')
Country.create(name: 'Afganistan')
Country.create(name: 'Aland Adaları')
Country.create(name: 'Almanya')
Country.create(name: 'Amerika Birleşik Devletleri')
Country.create(name: 'Amerika Birleşik Devletleri Küçük Dış Adaları')
Country.create(name: 'Amerikan Samoası')
Country.create(name: 'Andora')
Country.create(name: 'Angola')
Country.create(name: 'Anguilla')
Country.create(name: 'Antarktika')
Country.create(name: 'Antigua ve Barbuda')
Country.create(name: 'Arjantin')
Country.create(name: 'Arnavutluk')
Country.create(name: 'Aruba')
Country.create(name: 'Avrupa Birliği')
Country.create(name: 'Avustralya')
Country.create(name: 'Avusturya')
Country.create(name: 'Azerbaycan')
Country.create(name: 'Bahamalar')
Country.create(name: 'Bahreyn')
Country.create(name: 'Bangladeş')
Country.create(name: 'Barbados')
Country.create(name: 'Batı Sahara')
Country.create(name: 'Belize')
Country.create(name: 'Belçika')
Country.create(name: 'Benin')
Country.create(name: 'Bermuda')
Country.create(name: 'Beyaz Rusya')
Country.create(name: 'Bhutan')
Country.create(name: 'Bilinmeyen veya Geçersiz Bölge')
Country.create(name: 'Birleşik Arap Emirlikleri')
Country.create(name: 'Birleşik Krallık')
Country.create(name: 'Bolivya')
Country.create(name: 'Bosna Hersek')
Country.create(name: 'Botsvana')
Country.create(name: 'Bouvet Adası')
Country.create(name: 'Brezilya')
Country.create(name: 'Brunei')
Country.create(name: 'Bulgaristan')
Country.create(name: 'Burkina Faso')
Country.create(name: 'Burundi')
Country.create(name: 'Cape Verde')
Country.create(name: 'Cebelitarık')
Country.create(name: 'Cezayir')
Country.create(name: 'Christmas Adası')
Country.create(name: 'Cibuti')
Country.create(name: 'Cocos Adaları')
Country.create(name: 'Cook Adaları')
Country.create(name: 'Çad')
Country.create(name: 'Çek Cumhuriyeti')
Country.create(name: 'Çin')
Country.create(name: 'Danimarka')
Country.create(name: 'Dominik')
Country.create(name: 'Dominik Cumhuriyeti')
Country.create(name: 'Doğu Timor')
Country.create(name: 'Ekvator')
Country.create(name: 'Ekvator Ginesi')
Country.create(name: 'El Salvador')
Country.create(name: 'Endonezya')
Country.create(name: 'Eritre')
Country.create(name: 'Ermenistan')
Country.create(name: 'Estonya')
Country.create(name: 'Etiyopya')
Country.create(name: 'Falkland Adaları (Malvinalar)')
Country.create(name: 'Faroe Adaları')
Country.create(name: 'Fas')
Country.create(name: 'Fiji')
Country.create(name: 'Fildişi Sahilleri')
Country.create(name: 'Filipinler')
Country.create(name: 'Filistin Bölgesi')
Country.create(name: 'Finlandiya')
Country.create(name: 'Fransa')
Country.create(name: 'Fransız Guyanası')
Country.create(name: 'Fransız Güney Bölgeleri')
Country.create(name: 'Fransız Polinezyası')
Country.create(name: 'Gabon')
Country.create(name: 'Gambia')
Country.create(name: 'Gana')
Country.create(name: 'Gine')
Country.create(name: 'Gine-Bissau')
Country.create(name: 'Granada')
Country.create(name: 'Grönland')
Country.create(name: 'Guadeloupe')
Country.create(name: 'Guam')
Country.create(name: 'Guatemala')
Country.create(name: 'Guernsey')
Country.create(name: 'Guyana')
Country.create(name: 'Güney Afrika')
Country.create(name: 'Güney Georgia ve Güney Sandwich Adaları')
Country.create(name: 'Güney Kore')
Country.create(name: 'Güney Kıbrıs Rum Kesimi')
Country.create(name: 'Gürcistan')
Country.create(name: 'Haiti')
Country.create(name: 'Heard Adası ve McDonald Adaları')
Country.create(name: 'Hindistan')
Country.create(name: 'Hint Okyanusu İngiliz Bölgesi')
Country.create(name: 'Hollanda')
Country.create(name: 'Hollanda Antilleri')
Country.create(name: 'Honduras')
Country.create(name: 'Hong Kong SAR - Çin')
Country.create(name: 'Hırvatistan')
Country.create(name: 'Irak')
Country.create(name: 'İngiliz Virgin Adaları')
Country.create(name: 'İran')
Country.create(name: 'İrlanda')
Country.create(name: 'İspanya')
Country.create(name: 'İsrail')
Country.create(name: 'İsveç')
Country.create(name: 'İsviçre')
Country.create(name: 'İtalya')
Country.create(name: 'İzlanda')
Country.create(name: 'Jamaika')
Country.create(name: 'Japonya')
Country.create(name: 'Jersey')
Country.create(name: 'Kamboçya')
Country.create(name: 'Kamerun')
Country.create(name: 'Kanada')
Country.create(name: 'Karadağ')
Country.create(name: 'Katar')
Country.create(name: 'Kayman Adaları')
Country.create(name: 'Kazakistan')
Country.create(name: 'Kenya')
Country.create(name: 'Kiribati')
Country.create(name: 'Kolombiya')
Country.create(name: 'Komorlar')
Country.create(name: 'Kongo')
Country.create(name: 'Kongo Demokratik Cumhuriyeti')
Country.create(name: 'Kosta Rika')
Country.create(name: 'Kuveyt')
Country.create(name: 'Kuzey Kore')
Country.create(name: 'Kuzey Mariana Adaları')
Country.create(name: 'Küba')
Country.create(name: 'Kırgızistan')
Country.create(name: 'Laos')
Country.create(name: 'Lesotho')
Country.create(name: 'Letonya')
Country.create(name: 'Liberya')
Country.create(name: 'Libya')
Country.create(name: 'Liechtenstein')
Country.create(name: 'Litvanya')
Country.create(name: 'Lübnan')
Country.create(name: 'Lüksemburg')
Country.create(name: 'Macaristan')
Country.create(name: 'Madagaskar')
Country.create(name: 'Makao S.A.R. Çin')
Country.create(name: 'Makedonya')
Country.create(name: 'Malavi')
Country.create(name: 'Maldivler')
Country.create(name: 'Malezya')
Country.create(name: 'Mali')
Country.create(name: 'Malta')
Country.create(name: 'Man Adası')
Country.create(name: 'Marshall Adaları')
Country.create(name: 'Martinik')
Country.create(name: 'Mauritius')
Country.create(name: 'Mayotte')
Country.create(name: 'Meksika')
Country.create(name: 'Mikronezya Federal Eyaletleri')
Country.create(name: 'Moldovya Cumhuriyeti')
Country.create(name: 'Monako')
Country.create(name: 'Montserrat')
Country.create(name: 'Moritanya')
Country.create(name: 'Mozambik')
Country.create(name: 'Moğolistan')
Country.create(name: 'Myanmar')
Country.create(name: 'Mısır')
Country.create(name: 'Namibya')
Country.create(name: 'Nauru')
Country.create(name: 'Nepal')
Country.create(name: 'Nijer')
Country.create(name: 'Nijerya')
Country.create(name: 'Nikaragua')
Country.create(name: 'Niue')
Country.create(name: 'Norfolk Adası')
Country.create(name: 'Norveç')
Country.create(name: 'Orta Afrika Cumhuriyeti')
Country.create(name: 'Özbekistan')
Country.create(name: 'Pakistan')
Country.create(name: 'Palau')
Country.create(name: 'Panama')
Country.create(name: 'Papua Yeni Gine')
Country.create(name: 'Paraguay')
Country.create(name: 'Peru')
Country.create(name: 'Pitcairn')
Country.create(name: 'Polonya')
Country.create(name: 'Portekiz')
Country.create(name: 'Porto Riko')
Country.create(name: 'Reunion')
Country.create(name: 'Romanya')
Country.create(name: 'Ruanda')
Country.create(name: 'Rusya Federasyonu')
Country.create(name: 'Saint Helena')
Country.create(name: 'Saint Kitts ve Nevis')
Country.create(name: 'Saint Lucia')
Country.create(name: 'Saint Pierre ve Miquelon')
Country.create(name: 'Saint Vincent ve Grenadinler')
Country.create(name: 'Samoa')
Country.create(name: 'San Marino')
Country.create(name: 'Sao Tome ve Principe')
Country.create(name: 'Senegal')
Country.create(name: 'Seyşeller')
Country.create(name: 'Sierra Leone')
Country.create(name: 'Singapur')
Country.create(name: 'Slovakya')
Country.create(name: 'Slovenya')
Country.create(name: 'Solomon Adaları')
Country.create(name: 'Somali')
Country.create(name: 'Sri Lanka')
Country.create(name: 'Sudan')
Country.create(name: 'Surinam')
Country.create(name: 'Suriye')
Country.create(name: 'Suudi Arabistan')
Country.create(name: 'Svalbard ve Jan Mayen')
Country.create(name: 'Svaziland')
Country.create(name: 'Sırbistan')
Country.create(name: 'Sırbistan-Karadağ')
Country.create(name: 'Şili')
Country.create(name: 'Tacikistan')
Country.create(name: 'Tanzanya')
Country.create(name: 'Tayland')
Country.create(name: 'Tayvan')
Country.create(name: 'Togo')
Country.create(name: 'Tokelau')
Country.create(name: 'Tonga')
Country.create(name: 'Trinidad ve Tobago')
Country.create(name: 'Tunus')
Country.create(name: 'Turks ve Caicos Adaları')
Country.create(name: 'Tuvalu')
Country.create(name: 'Türkmenistan')
Country.create(name: 'Uganda')
Country.create(name: 'Ukrayna')
Country.create(name: 'Umman')
Country.create(name: 'Uruguay')
Country.create(name: 'Uzak Okyanusya')
Country.create(name: 'Ürdün')
Country.create(name: 'Vanuatu')
Country.create(name: 'Vatikan')
Country.create(name: 'Venezuela')
Country.create(name: 'Vietnam')
Country.create(name: 'Wallis ve Futuna')
Country.create(name: 'Yemen')
Country.create(name: 'Yeni Kaledonya')
Country.create(name: 'Yeni Zelanda')
Country.create(name: 'Yunanistan')
Country.create(name: 'Zambiya')
Country.create(name: 'Zimbabve')
City.create(country_id: 1, name: 'Adana')
City.create(country_id: 1, name: 'Adıyaman')
City.create(country_id: 1, name: 'Afyonkarahisar')
City.create(country_id: 1, name: 'Ağrı')
City.create(country_id: 1, name: 'Aksaray')
City.create(country_id: 1, name: 'Amasya')
City.create(country_id: 1, name: 'Ankara')
City.create(country_id: 1, name: 'Antalya')
City.create(country_id: 1, name: 'Ardahan')
City.create(country_id: 1, name: 'Artvin')
City.create(country_id: 1, name: 'Aydın')
City.create(country_id: 1, name: 'Balıkesir')
City.create(country_id: 1, name: 'Bartın')
City.create(country_id: 1, name: 'Batman')
City.create(country_id: 1, name: 'Bayburt')
City.create(country_id: 1, name: 'Bilecik')
City.create(country_id: 1, name: 'Bingöl')
City.create(country_id: 1, name: 'Bitlis')
City.create(country_id: 1, name: 'Bolu')
City.create(country_id: 1, name: 'Burdur')
City.create(country_id: 1, name: 'Bursa')
City.create(country_id: 1, name: 'Çanakkale')
City.create(country_id: 1, name: 'Çankırı')
City.create(country_id: 1, name: 'Çorum')
City.create(country_id: 1, name: 'Denizli')
City.create(country_id: 1, name: 'Diyarbakır')
City.create(country_id: 1, name: 'Düzce')
City.create(country_id: 1, name: 'Edirne')
City.create(country_id: 1, name: 'Elazığ')
City.create(country_id: 1, name: 'Erzincan')
City.create(country_id: 1, name: 'Erzurum')
City.create(country_id: 1, name: 'Eskişehir')
City.create(country_id: 1, name: 'Gaziantep')
City.create(country_id: 1, name: 'Giresun')
City.create(country_id: 1, name: 'Gümüşhane')
City.create(country_id: 1, name: 'Hakkâri')
City.create(country_id: 1, name: 'Hatay')
City.create(country_id: 1, name: 'Iğdır')
City.create(country_id: 1, name: 'Isparta')
City.create(country_id: 1, name: 'İstanbul')
City.create(country_id: 1, name: 'İzmir')
City.create(country_id: 1, name: 'Kahramanmaraş')
City.create(country_id: 1, name: 'Karabük')
City.create(country_id: 1, name: 'Karaman')
City.create(country_id: 1, name: 'Kars')
City.create(country_id: 1, name: 'Kastamonu')
City.create(country_id: 1, name: 'Kayseri')
City.create(country_id: 1, name: 'Kilis')
City.create(country_id: 1, name: 'Kırıkkale')
City.create(country_id: 1, name: 'Kırklareli')
City.create(country_id: 1, name: 'Kırşehir')
City.create(country_id: 1, name: 'Kocaeli')
City.create(country_id: 1, name: 'Konya')
City.create(country_id: 1, name: 'Kütahya')
City.create(country_id: 1, name: 'Malatya')
City.create(country_id: 1, name: 'Manisa')
City.create(country_id: 1, name: 'Mardin')
City.create(country_id: 1, name: 'Mersin')
City.create(country_id: 1, name: 'Muğla')
City.create(country_id: 1, name: 'Muş')
City.create(country_id: 1, name: 'Nevşehir')
City.create(country_id: 1, name: 'Niğde')
City.create(country_id: 1, name: 'Ordu')
City.create(country_id: 1, name: 'Osmaniye')
City.create(country_id: 1, name: 'Rize')
City.create(country_id: 1, name: 'Sakarya')
City.create(country_id: 1, name: 'Samsun')
City.create(country_id: 1, name: 'Şanlıurfa')
City.create(country_id: 1, name: 'Siirt')
City.create(country_id: 1, name: 'Sinop')
City.create(country_id: 1, name: 'Sivas')
City.create(country_id: 1, name: 'Şırnak')
City.create(country_id: 1, name: 'Tekirdağ')
City.create(country_id: 1, name: 'Tokat')
City.create(country_id: 1, name: 'Trabzon')
City.create(country_id: 1, name: 'Tunceli')
City.create(country_id: 1, name: 'Uşak')
City.create(country_id: 1, name: 'Van')
City.create(country_id: 1, name: 'Yalova')
City.create(country_id: 1, name: 'Yozgat')
City.create(country_id: 1, name: 'Zonguldak')


100.times{|x| Company.create(name:  "#{(0...4).map { (65 + rand(26)).chr }.join} Company")}